/**
 * Verifies the localized SEO metadata generated by the App Router pages:
 * descriptions, canonical URLs and en/it alternates.
 */

jest.mock("next-intl/server", () => ({
  getTranslations: async () => (key: string) => key,
  getMessages: async () => ({}),
  getLocale: async () => "en",
}));

import { generateMetadata as summaryMetadata } from "@/app/[locale]/configure/[modelId]/summary/page";
import { generateMetadata as homeMetadata } from "@/app/[locale]/page";

function params(values: Record<string, string>) {
  return { params: Promise.resolve(values) } as never;
}

describe("summary page metadata", () => {
  it("includes a localized description and canonical URL (en)", async () => {
    const meta = await summaryMetadata(params({ locale: "en", modelId: "natural-glow" }));
    expect(meta.title).toContain("Natural Glow");
    expect(meta.description).toBe("A fresh, everyday look that enhances your natural features");
    expect(meta.alternates?.canonical).toBe("/en/configure/natural-glow/summary");
    expect(meta.alternates?.languages).toMatchObject({
      en: "/en/configure/natural-glow/summary",
      it: "/it/configure/natural-glow/summary",
    });
  });

  it("localizes the description in Italian", async () => {
    const meta = await summaryMetadata(params({ locale: "it", modelId: "natural-glow" }));
    expect(meta.description).toBe("Un look fresco e quotidiano che esalta i tuoi tratti naturali");
    expect(meta.alternates?.canonical).toBe("/it/configure/natural-glow/summary");
  });

  it("returns empty metadata for an unknown look", async () => {
    const meta = await summaryMetadata(params({ locale: "en", modelId: "does-not-exist" }));
    expect(meta).toEqual({});
  });
});

describe("home page metadata", () => {
  it("includes a localized description and canonical URL per locale", async () => {
    const en = await homeMetadata(params({ locale: "en" }));
    expect(en.description).toBeTruthy();
    expect(en.alternates?.canonical).toBe("/en");

    const it = await homeMetadata(params({ locale: "it" }));
    expect(it.description).toContain("look");
    expect(it.alternates?.canonical).toBe("/it");
  });
});
